# **Fundamentals of TensorFlow.**

In [1]:
# Tensorflow purpose: turn data into numbers (tensors) and build machine learning algorithms to find patterns in them.

# Create timestamp.
# import datetime

# print("------------------------------------")
# print(f"Notebook last run (end-to-end): {datetime.datetime.now()}")
# print("------------------------------------")

'''
# tensors are kind of like NumPy arrays. Tensor as a multi-dimensional numerical representation of something. (Also, referred to as n-dimensional, where n can be any number).
-> Using tensors to represent the price of houses.
-> Using tensors to represent the pixels of an image.
-> Using tensors to represent words.
-> Or it could be some other form of information (or data) you want to represent with numbers

# Note:
The main difference between `tensors` and `NumPy arrays` (also an n-dimensional array of numbers) is that tensors can be used on GPUs (graphical processing units) and TPUs (tensor processing units).
'''

# print("------------------------------------")
import tensorflow as tf
# print("\n Tensorflow Version: ",tf.__version__)
# print("------------------------------------")

# A scalar is known as a rank 0 tensor. Because it has no dimensions (it's just a number).
# Create a scalar (rank 0 tensor).
print("------------------------------------")
scalar = tf.constant(7)
print(scalar)
print("------------------------------------")

print("------------------------------------")
print("\nChecking the number of dimensions of a tensor: (ndim stands for number of dimensions.)")
print(scalar.ndim)


print("\nCreate a vector (more than 0 dimensions.)")
vector = tf.constant([10, 10])
print(vector)
print("\nDimension of vector: ", vector.ndim)

print("\nCreate a matrix (more than 1 dimension)")
matrix = tf.constant([[10, 7],
[7, 10]])
print(matrix)

print("\n# Create another matrix and define the datatype")
another_matrix = tf.constant([[10., 7.],
                        [3., 2.],
                        [8., 9.]], dtype=tf.float16) # specify the datatypes wiuth 'dtype'.

print(another_matrix)
print("# Even though another_matrix contains more numbers, its dimension stay the same: ", another_matrix.ndim)

print("\n # How about a tensor? (more than 2 dimensions, although, all of the above items are also technically tensors.")
tensor = tf.constant([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9],[10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
                    ])
print(tensor)
print("shape of tensor: ", tensor.ndim)
print("------------------------------------")

'''
The above is known as a rank 3 tensor (3-dimensions), however a tensor can have an arbitrary (unlimited) amount of dimensions.

For example, you might turn a series of images into tensors with shape (224, 224, 3, 32), where:
    -> 224, 224 (the first 2 dimensions) are the height and width of the images in pixels.
    -> 3 is the number of colour channels of the image (red, green blue).
    -> 32 is the batch size (the number of images a neural network sees at any one time).

Note:
a. scalar: a single number.
b. vector: a number with direction (e.g. wind speed with direction).
c. matrix: a 2-dimensional array of numbers.
d. tensor: an n-dimensional arrary of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).

# To add to the confusion, the terms matrix and tensor are often used interchangably.
'''


print("\n------------------------------------------------------------")
print("# Creating Tensors with tf.Variable()")
# Create the same tensor with tf.Variable() and tf.constant()
changeable_tensors = tf.Variable([10, 7])
unchangeable_tensors = tf.constant([10, 7])
print(changeable_tensors, unchangeable_tensors)

# Let's try to change the one element of the changeable tensors.

# changeable_tensors[0] = 7 # will through an error (because it requires an .assign() method).

changeable_tensors[0].assign(90)
print(changeable_tensors)

# But if we try to change a value in tf.constant() tensor.

# unchangeable_tensors[0].assign(78) # Will error (can't change tf.constant())
# print(unchangeable_tensors)


'''
# Which one should you use? tf.constant() or tf.Variable()?
=> It will depend on what your problem requires. However, most of the time, TensorFlow will automatically choose for you (when loading data or modelling data).

# Why would you want to create random tensors?
=> This is what neural networks use to intialize their weights (patterns) that they're trying to learn in the data.
For example, the process of a neural network learning often involves taking a random n-dimensional array of numbers and refining them until they represent some kind of pattern (a compressed way to represent the original data).

- A network learns by starting with random patterns (1) then going through demonstrative examples of data (2) whilst trying to update its random patterns to represent the examples (3).
'''


print("# We can create random tensors by using the tf.random.Generator class.")
print("# Create two random (but the same) tensors. ")
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility.
random_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution.

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

print("Random Number 1: ", random_1)
print("Random Number 2: ", random_2)

# Are they equal ?
# print(random_1, random_2, random_1 == random_2)


# Create two random (and different) tensors.
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))

random_4 = tf.random.Generator.from_seed(42)
random_4 = random_4.normal(shape=(3, 2))

# Check the tensors and see if they are equal.
print(random_3, random_4, random_1 == random_3, random_3 == random_4)

------------------------------------
tf.Tensor(7, shape=(), dtype=int32)
------------------------------------
------------------------------------

Checking the number of dimensions of a tensor: (ndim stands for number of dimensions.)
0

Create a vector (more than 0 dimensions.)
tf.Tensor([10 10], shape=(2,), dtype=int32)

Dimension of vector:  1

Create a matrix (more than 1 dimension)
tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)

# Create another matrix and define the datatype
tf.Tensor(
[[10.  7.]
 [ 3.  2.]
 [ 8.  9.]], shape=(3, 2), dtype=float16)
# Even though another_matrix contains more numbers, its dimension stay the same:  2

 # How about a tensor? (more than 2 dimensions, although, all of the above items are also technically tensors.
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)
shape of tensor:  3
------------------------------------

------------------------------------------------

In [2]:
#  What if you wanted to shuffle the order of a tensor ?
# Let's say you working with 15,000 images of cats and dogs and the first 10,000 images of were of cats and the next 5,000 were of dogs. This order could effect how a neural network learns (it may overfit by learning the order of the data), instead, it might be a good idea to move your data around.

print("# shuffle a tensor (valuable for when we want to shuffle our data)")
not_shuffled = tf.random.Generator.from_seed(42)
not_shuffled = not_shuffled.normal(shape=(3, 2))

# Get different results each time.
print("Getting an different tensors each time runs: ")
print(tf.random.shuffle(not_shuffled))

print("\n------------------------------------------------------------")

# shuffle a tensor (valuable for when we want to shuffle our data)
Getting an different tensors each time runs: 
tf.Tensor(
[[ 0.07595026 -1.2573844 ]
 [-0.7565803  -0.06854702]
 [-0.23193765 -1.8107855 ]], shape=(3, 2), dtype=float32)

------------------------------------------------------------


In [3]:
# shuffled a tensor (valuable for when we want to shuffle our data.)
print("--- With Constant ---")
not_shuffled_constant_data = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

# Gives the different result each time run.
tf.random.shuffle(not_shuffled_constant_data, seed=42)

--- With Constant ---


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [4]:
# Shuffle in the same order every time using the seed parameter (won't actually be the same).
tf.random.shuffle(not_shuffled_constant_data, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

**Observations:**

Q. Why did't the numbers come out the same ?>

It's due to rule #4 of the `tf.random.set_seed()`

> Note: If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [5]:
# shuffle in the same order every time.

# set the global random seed.
tf.random.set_seed(42)

# set the operation random seed.
tf.random.shuffle(not_shuffled_constant_data, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [6]:
# Other ways to make tensors.

print("--- Make a tensor of all ones ---")
print(tf.ones(shape=(3, 2)))

print("\n--- Make a tensor of all zeros ---")
print(tf.zeros(shape=(3, 2)))

--- Make a tensor of all ones ---
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)

--- Make a tensor of all zeros ---
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


> 🔑 Note: A matrix or tensor is typically represented by a capital letter (e.g. X or A) where as a vector is typically represented by a lowercase letter (e.g. y or b).

In [7]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25.
A = tf.constant(numpy_A, shape=[2, 3, 4]) # Note: the shape total (2*4*3) has to match the number of elements in the array.
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

### Getting information from tensors (shape, rank, size)

> **Shape:** The length (number of elements) of each of the dimensions of a tensor.

> **Rank:** The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.

> **Axis or Dimension:** A particular dimension of a tensor.

> **Size:** The total number of items in the tensor.

In [8]:
# Create a rank 4 tensor (4 dimensions.)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [9]:
(
    "Rank: ", rank_4_tensor.ndim,
    "Shape:", rank_4_tensor.shape,
    "Size: ",tf.size(rank_4_tensor)
)

('Rank: ',
 4,
 'Shape:',
 TensorShape([2, 3, 4, 5]),
 'Size: ',
 <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [10]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [11]:
# Get the first 2 items of each dimension.
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [12]:
# Get the dimension from each index except for the final one.
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [13]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
# Get the last item of each row.
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

we can also add dimension to your tensor whilst keeping the same information present using `tf.newaxis`.

In [14]:
# Add an extra dimension (to the end).
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor # shape (2, 2), shape (2, 2, 1)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

We can achieve the same using `tf.expand_dims()`.


In [15]:
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means last axis.

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

Finding patterns in tensors (numberical representation of data) requires manipulating them.

In [16]:
# Basic Operations.

# Add an values to a tensor using the addition operator.
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [17]:
#  Since, we used tf.constant(), the original tensor is unchanged (the addition gets done on a copy).
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [18]:
# Multiplication (known as element-wise multiplication)
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [19]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [20]:
# we can also use the equivalent `TensorFlow` Function.

# Use the tensorflow function equivalent of the "*" (mutiply) operator.
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [21]:
# The original tensor is still unchanged.
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [22]:
# Matrix mutliplication.

# matmul() method.
'''
1. The inner dimensions must match:
    -> (3, 5) @ (3, 5) won't work.
    -> (5, 3) @ (3, 5) will work.
    -> (3, 5) @ (5, 3) will work.

2. The resulting matrix has the shape of the outer dimensions:
    -> (5, 3) @ (3, 5) -> (5, 5).
    -> (3, 5) @ (5, 3) -> (3, 3).

Note: '@' in Python is the symbol for matrix multiplication.
'''

# Matrix multiplication in TensorFlow.
print(tensor)
print("-----------------------------------------------")
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
-----------------------------------------------


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [23]:
# Matrix multiplication with Python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [24]:
# Create (3, 2) tensor.
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create (3, 2) tensor.
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [25]:
# Try to matrix multiply them (will error)
X @ Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

**Observation:**

Trying to matrix multiply two tensors with the shape `(3, 2)` errors because the inner dimensions don't match.

We need to either:

*   Reshape X to `(2, 3)` so it's `(2, 3)` @ `(3, 2)`.
*   Reshape Y to `(3, 2)` so it's `(3, 2)` @ `(2, 3)`.

We can do this with either:

*   `tf.reshape()` - allows us to reshape a tensor into a defined shape.
*   `tf.transpose()` - switches the dimensions of a given tensor.

In [26]:
X = tf.transpose(X)

In [27]:
# # Try matrix multiplication with reshaped Y
# X @ tf.reshape(Y, shape=(2, 3))

In [28]:
X @ Y # Now the multiplication of the two matrix will works.

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [29]:
# Reshapping works like this.
'''
tf.reshape(Y, shape=(2, 3))
'''

'\ntf.reshape(Y, shape=(2, 3))\n'

In [30]:
#  It worked, let's try the same with a reshaped X, except this time we'll use tf.transpose() and tf.matmul()

In [31]:
# we can also achieve the same "result" with parameters.
# tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

### The dot product

In [32]:
# Multiplying matrices by eachother is also referred to as the dot product.

# we can also perform the tf.matmul() operation using tf.tensordot().

# Perform the dot product on X and Y (requires X to be transposed).
X = tf.constant([[1, 2], [2, 3], [4, 5]])
Y = tf.constant([[2, 7], [6, 8], [9, 11]])

# matrix multiplication with `tensordot()`.
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 67],
       [67, 93]], dtype=int32)>

In [33]:
# Performing the matrix multiplication between X and Y (transposed).
X = tf.transpose(X)
tf.matmul(X, Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 67],
       [67, 93]], dtype=int32)>

In [34]:
# Performing matrix multiplication between X and Y (reshaped).
X = tf.reshape(X, (2, 3))
tf.matmul(X, Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 67],
       [67, 93]], dtype=int32)>

In [35]:
# Check shapes of Y, reshaped Y and tranposed Y
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))


But calling `tf.reshape()` and `tf.transpose()` on Y don't necessarily result in the same values.

In [36]:
# Check values of Y, reshape Y and tranposed Y
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 2  7]
 [ 6  8]
 [ 9 11]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 2  7  6]
 [ 8  9 11]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 2  6  9]
 [ 7  8 11]], shape=(2, 3), dtype=int32)


**Explanation:**



*   `tf.reshape()` - Change the shape of the given tensor (first) & then insert values in order they appear.
*   `tf.transpose()` - swap the order of the axes, by default the last axis becomes the first, however the order can be changed using the `perm` parameter.



### Changing the datatype of a tensor

In [37]:
# # Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

# # Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [38]:
# Change from the float32 to float16 (reduced the precision).
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [39]:
# Change from int32 to float32
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

### Getting the absolute value

In [40]:
# absolute value: all positive values.

# Create tensor with negative values.
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [41]:
# Get the absolute values.
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### Finding the min, max, mean, sum (aggregation)

Implemented with `reduce()_[action]`.



*   `tf.reduce_min()` - find the minimum value in a tensor.
*   `tf.reduce_max()` - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
*   `tf.reduce_mean()` - find the mean of all elements in a tensor.
*   `tf.reduce_sum()` - find the sum of all elements in a tensor.


`tf.math.reduce_min()`

In [42]:
# Create a tensor with 50 random values between 0 and 100.
E = tf.constant(np.random.randint(
    low=0,
    high=100,
    size=50
))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 6, 88, 71, 62, 94, 74,  3, 37, 20, 51, 83, 88, 42, 44, 27, 66, 14,
        0, 38,  8, 46, 94, 90, 27, 25, 34, 26, 42, 36,  4, 20, 60, 88, 12,
       41, 52, 90, 28, 94, 80, 24,  0, 49, 12, 83, 95, 37, 90, 31, 63])>

In [43]:
# Find the minimum.
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [44]:
# Find the maximum.
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=95>

In [45]:
# Find the mean.
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [46]:
# Find the sum.
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2389>

In [47]:
# Find the standard deviation.
# tf.reduce_std(E)

In [48]:
# Find the variation.
# tf.reduce_variance(E)

### Finding the positional maximum and minimum

How about finding the position a tensor where the maximum value occurs?

This is helpful when you want to line up your labels (say ['Green', 'Blue', 'Red']) with your prediction probabilities tensor (e.g. [0.98, 0.01, 0.01]).

In this case, the predicted label (the one with the highest prediction probability) would be 'Green'.

We can do the same for the minimum (if required) with the following:

*   `tf.argmax()` - find the position of the maximum element in a given tensor.
*   `tf.argmin()` - find the position of the minimum element in a given tensor.


In [49]:
# Create a tensor with 50 values between 0 and 1
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.7439357 , 0.9348634 , 0.22125041, 0.44461487, 0.76166461,
       0.23605083, 0.97492631, 0.51491235, 0.37686361, 0.68373245,
       0.73744982, 0.59765311, 0.65728376, 0.17811499, 0.1416308 ,
       0.27651855, 0.91981693, 0.42474553, 0.15290142, 0.05492195,
       0.12700752, 0.52965653, 0.16827944, 0.85297825, 0.16166407,
       0.94391294, 0.14017189, 0.91040368, 0.40455269, 0.4646662 ,
       0.95356597, 0.31939524, 0.10827709, 0.68303082, 0.6432512 ,
       0.69675085, 0.09689215, 0.72461135, 0.7649648 , 0.68590588,
       0.41074855, 0.48015008, 0.14838261, 0.58418332, 0.28061185,
       0.72127883, 0.75417825, 0.89473104, 0.77404734, 0.23960727])>

In [50]:
# Find the position of maximum element of F.
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [51]:
# Find the minimum element position of F
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=19>

In [52]:
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}")
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}")
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 6
The maximum value of F is: 0.9749263104301622
Using tf.argmax() to index F, the maximum value of F is: 0.9749263104301622
Are the two max values the same (they should be)? True


### Squeezing a tensor (removing all single dimensions)

In [53]:
# If we want to remove the single-dimensions from a tensor (dimensionw with size 1), then we can use `tf.squeeze()`.

# tf.squeeze() - remove all dimensions of 1 from a tensor.

# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100.
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [54]:
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

### One-Hot Encoding.

In [55]:
# If we have a tensor of indices and would like to one-hot encode it, we can use tf.one_hot().

# we should also specify the `depth` parameter (the level which we want to one-hot encode to).

# Create a list of indices.
some_list = [0, 1, 2, 3]

# One hot encode them.
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [56]:
# We can also specify values for `on_values` and `off_values` instead of default `0` and `1`.

# Specify custom values for on and off encoding
tf.one_hot(some_list, depth=4, on_value="We're live!", off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're live!", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're live!", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're live!", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're live!"]], dtype=object)>

### Squaring, log, square root

*   `tf.square()` - get the square of every value in a tensor.
*   `tf.sqrt()` - get the squareroot of every value in a tensor (note: the elements need to be floats or this will error).
*   `tf.math.log()` - get the natural log of every value in a tensor (elements need to floats).

In [57]:
# Create a new tensor.
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [58]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [59]:
# Find the squareroot (will error), needs to be non-integer
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int64 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [60]:
# Change H to float32.
H = tf.cast(H, dtype=tf.float32)
H

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [61]:
# Find the square root.
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [62]:
# Find the log (input also needs to be float.)
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Manipulating `tf.Variable` tensors.


*   `.assign()` - assign a different value to a particular index of a variable tensor.
*   `.add_assign()` - add to an existing value and reassign it at a particular index of a variable tensor.



In [63]:
# Create a variable tensor.
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [64]:
# Assing the final value a new value of 50.
I.assign([0, 1, 2, 3, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [65]:
# The change happes in place (the last value is now 50, nto 4)
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [66]:
# Add 10 to every element in I.
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

In [67]:
# Again, the change happens in place
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

### Tensors and NumPy

Tensors can also be converted to NumPy arrays using:

* `np.array()` - pass a tensor to convert to an ndarry (NumPy's main datatype).
* `tensor.numpy()` - call on a tensor to convert to an ndarray.

In [68]:
# Create a tensor from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [69]:
# Convert the tensor J too NumPy with np.array()
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [70]:
# Convert tensor J to NumPy with .numpy()
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

By default tensors have `dtype=float32`, where as NumPy arrays have `dtype=float64`.

This is because neural networks (which are usually built with TensorFlow) can generally work very well with less precision (32-bit rather than 64-bit).

In [71]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)

tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Using `@tf.function`

[Click Me to check `Decorator Function in Python`](https://realpython.com/primer-on-python-decorators/#first-class-objects)

In [72]:
# In the @tf.function decorator case, it turns a Python function into a callable TensorFlow graph.Which is a fancy way of saying, if we've written your own Python function, and you decorate it with @tf.function, when you export your code (to potentially run on another device), TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).

In [73]:
# Creating a simple function.
def function(x, y):
    return x**2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
print("------------------------------------------------------------------------")
print(function(x, y))


# Create the same function and decorate it with tf.function.
@tf.function
def tf_function(x, y):
    return x**2 + y
print("\n------------------------------------------------------------------------")
print(tf_function(x, y))

------------------------------------------------------------------------
tf.Tensor([ 10  12  16  22  30  40  52  66  82 100], shape=(10,), dtype=int64)

------------------------------------------------------------------------
tf.Tensor([ 10  12  16  22  30  40  52  66  82 100], shape=(10,), dtype=int64)


`Conclusion:` we can noticed no difference between the above two functions (the decorate one and the non-decorated one).
But much of the difference happens behind the scens. One of the main ones being potential code speed-ups where possible.

### Finding access to GPUs

In [74]:
# Check if gpu is available.
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [75]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


# **Exercises**

In [91]:
# Q1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
scalar = tf.constant(12)
print("\nScalar: ", scalar)

vector = tf.constant([1, 2])
print("\nVector: ", vector)

matrix = tf.constant([[1, 2, 4, 5],
 [2, 3, 6, 7]])
print("\nMatrix: ", matrix)

tensor = tf.constant([[[1, 2, 3],[4, 5, 6], [1, 4, 7]], [[4, 1, 3],[1, 5, 4], [9, 2, 1]]])
print("\nConstant: ", tensor)


Scalar:  tf.Tensor(12, shape=(), dtype=int32)

Vector:  tf.Tensor([1 2], shape=(2,), dtype=int32)

Matrix:  tf.Tensor(
[[1 2 4 5]
 [2 3 6 7]], shape=(2, 4), dtype=int32)

Constant:  tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [1 4 7]]

 [[4 1 3]
  [1 5 4]
  [9 2 1]]], shape=(2, 3, 3), dtype=int32)


In [130]:
# Q2. Find the shape, rank and size of the tensors you created in 1.
print("--------- scalar ---------")
print("shape: ", scalar.shape)
print("rank or number of dimensions: ", scalar.ndim, tf.size(scalar))
print("size: ", tf.size(scalar))

print("\n--------- vector ---------")
print("shape: ", vector.shape)
print("rank or number of dimensions: ", vector.ndim)
print("size: ", tf.size(vector))

print("\n--------- matrix ---------")
print("shape: ", matrix.shape)
print("rank or number of dimensions: ", matrix.ndim)
print("size: ", tf.size(matrix))

print("\n--------- tensor ---------")
print("shape: ", tensor.shape)
print("rank or number of dimensions: ", tensor.ndim)
print("size: ", tf.size(tensor))

--------- scalar ---------
shape:  ()
rank or number of dimensions:  0 tf.Tensor(1, shape=(), dtype=int32)
size:  tf.Tensor(1, shape=(), dtype=int32)

--------- vector ---------
shape:  (2,)
rank or number of dimensions:  1
size:  tf.Tensor(2, shape=(), dtype=int32)

--------- matrix ---------
shape:  (2, 4)
rank or number of dimensions:  2
size:  tf.Tensor(8, shape=(), dtype=int32)

--------- tensor ---------
shape:  (2, 3, 3)
rank or number of dimensions:  3
size:  tf.Tensor(18, shape=(), dtype=int32)


In [134]:
# Q3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

# setting the random seed.
tf.random.set_seed(42)

tensor_A = tf.random.uniform(shape=(5, 300))
tensor_B = tf.random.uniform(shape=(5, 300))

print("Tensor A: ")
print(tensor_A)
print(tensor_A.shape)

print("\nTensor B: ")
print(tensor_B)
print(tensor_B.shape)

Tensor A: 
tf.Tensor(
[[0.6645621  0.44100678 0.3528825  ... 0.31410468 0.7593535  0.03699052]
 [0.532024   0.29129946 0.10571766 ... 0.54052293 0.31425726 0.2200619 ]
 [0.08404207 0.03614604 0.97732127 ... 0.21516645 0.9786098  0.00726748]
 [0.7396945  0.6653172  0.0787828  ... 0.7117733  0.07013571 0.9409125 ]
 [0.15861344 0.12024033 0.27218235 ... 0.8824879  0.1432488  0.44135118]], shape=(5, 300), dtype=float32)
(5, 300)

Tensor B: 
tf.Tensor(
[[0.68789124 0.48447883 0.9309944  ... 0.6920762  0.33180213 0.9212563 ]
 [0.27369928 0.10631859 0.6218617  ... 0.4382149  0.30427706 0.51477313]
 [0.00920248 0.37280262 0.8177401  ... 0.56786287 0.49201214 0.9892651 ]
 [0.88608265 0.08672249 0.12160683 ... 0.91770685 0.72545695 0.8280058 ]
 [0.36690474 0.9200133  0.9646884  ... 0.69012    0.7137332  0.2584542 ]], shape=(5, 300), dtype=float32)
(5, 300)


In [137]:
# Q4. Multiply the two tensors created in 3 using matrix multiplication.
print('Shape before the matrix multiplication')
print(tensor_A.shape , '\n')
print(tensor_B.shape , '\n')

# tensor_A @ tf.transpose(tensor_B) # here, we can also use the reshape function but fine.

resultant_vector = tf.linalg.matmul(tensor_A, tf.transpose(tensor_B))
print(f'After multiplying the resultant vector is: {resultant_vector} \n')

print(f'The resultant vector shape: {resultant_vector.shape}')

Shape before the matrix multiplication
(5, 300) 

(5, 300) 

After multiplying the resultant vector is: [[80.333435 73.40498  77.15961  73.98368  80.90053 ]
 [75.14637  68.80438  74.24303  71.84184  75.60205 ]
 [79.7594   75.64456  77.79758  74.748726 80.55984 ]
 [75.085266 69.06408  74.30776  72.27615  76.05667 ]
 [85.05689  74.26629  78.00687  74.886795 83.13417 ]] 

The resultant vector shape: (5, 5)


In [138]:
# Q5. Multiply the two tensors we created in 3 using dot product.
tf.tensordot(tf.transpose(tensor_A), tensor_B, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.317161  , 0.61993605, 1.2612379 , ..., 1.5290778 , 1.0735596 ,
        1.6227092 ],
       [1.0170685 , 0.42642498, 0.8181824 , ..., 1.1469344 , 0.8212255 ,
        1.1739546 ],
       [0.45034647, 0.8037954 , 1.4656199 , ..., 1.105671  , 0.88152766,
        1.481925  ],
       ...,
       [1.3204696 , 1.1634867 , 1.7423928 , ..., 1.8386563 , 1.5207756 ,
        1.5979093 ],
       [0.73207504, 0.90400356, 1.8493464 , ..., 1.3821819 , 0.98218614,
        1.924531  ],
       [1.0814031 , 0.5316744 , 0.7174167 , ..., 1.2942287 , 1.0804075 ,
        1.0476992 ]], dtype=float32)>

In [140]:
# Q6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
image_tensor = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)
image_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[7.4023080e-01, 3.3938193e-01, 5.6925058e-01],
        [4.4811392e-01, 2.9285502e-01, 4.2600560e-01],
        [6.2890387e-01, 6.9106102e-01, 3.0925727e-01],
        ...,
        [9.1063976e-04, 6.9863999e-01, 1.7180574e-01],
        [6.7542684e-01, 8.3492923e-01, 3.9038682e-01],
        [2.3664141e-01, 6.2239432e-01, 1.0117912e-01]],

       [[9.7064960e-01, 5.4594779e-01, 7.6819682e-01],
        [2.6893330e-01, 2.6959443e-01, 2.8982997e-01],
        [2.9215467e-01, 1.7108858e-01, 6.5597153e-01],
        ...,
        [9.5621395e-01, 5.4591870e-01, 5.3843534e-01],
        [9.8861516e-01, 1.5786767e-01, 6.1375093e-01],
        [7.2668612e-01, 6.1637163e-03, 1.6534305e-01]],

       [[6.4095867e-01, 7.6697862e-01, 3.0138540e-01],
        [1.5474892e-01, 1.7183411e-01, 2.7192724e-01],
        [3.1211805e-01, 6.1451709e-01, 4.3001354e-01],
        ...,
        [8.4168065e-01, 5.0247252e-01, 2.8834987e-01],
        [3.3173549e-01

In [142]:
# Q7. Find the min and max values of the tensor you created in 6.
print(f"Minimum value: {tf.reduce_min(image_tensor)}")
print(f"Maximum value: {tf.reduce_max(image_tensor)}")

Minimum value: 1.0967254638671875e-05
Maximum value: 0.9999902248382568


In [144]:
# Q8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]

# Tensor with shape [224, 224, 3]
unsqueezed_tensor = tf.random.Generator.from_seed(42)
unsqueezed_tensor = unsqueezed_tensor.normal(shape = (1, 224, 224, 3))

print(f"The shape before squeezing: {unsqueezed_tensor.shape}")

The shape before squeezing: (1, 224, 224, 3)


In [145]:
# And now, we are squeezing the tensor.
squeezed_tensor = tf.squeeze(unsqueezed_tensor)
print(f"The shape after squeezing: {squeezed_tensor.shape}")

The shape after squeezing: (224, 224, 3)


In [146]:
# Q9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
ten_tensor = tf.constant([0 ,1 ,2 ,3, 4, 9, 10, 0.1 , -000.1 , 6])

# Finding the index where value is maximum.
max_value = tf.math.argmax(ten_tensor)

print(f'The indices where the value is maximum: {max_value}')
print(f'The maximum value was: {ten_tensor[max_value]}')

The indices where the value is maximum: 6
The maximum value was: 10.0


In [149]:
# Q10. One-hot encode the tensor you created in 9.
value_to_encode = tf.cast(ten_tensor, dtype=tf.int32)

In [150]:
# One hot encoding the tensor of shape 10.
tf.one_hot(value_to_encode, dtype=tf.int32, depth=10)

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0]], dtype=int32)>